### ISSUE TITLE
Certificate not removed from certificate store upon uninstall

### ISSUE THREAD

**Issue by ingmar** [yoshiask/FluentStore#15]
After uninstallation of FluentStore, the certificate with `CN = CD3113F3-18EB-4B8D-9D8A-C6D373E7A464` remains in the certificate store and has to be manually deleted.

**Comment by yoshiask** [comment]
Starting with the release of v0.3.0-beta, installers are signed with a trusted certificate so the previous workaround is no longer necessary.
