### ISSUE TITLE
HTTP 400: Bad Request on workstation with org's proxy 

### ISSUE THREAD

**Issue by Al3xDroid** [yoshiask/FluentStore#28]
Hello
I have tried your app in intranet area with my Windows desktop managed via Microsoft Domain and a proxy server for internet access. Your app don't recognize a system proxy settings of my workstation.
Cheers

![Cattura](https://user-images.githubusercontent.com/97443778/148756543-25793d2a-8bd9-42bc-bad3-b0db8192138b.PNG)

**Comment by yoshiask** [comment]
Howdy! Can you try copying that URL into a browser and seeing if you get the same error there?

**Comment by Al3xDroid** [comment]
result with chrome (windows 10 64bit)

![image](https://user-images.githubusercontent.com/97443778/148939612-b56fe026-f97a-44d1-8c64-def4440a77ca.png)

**Comment by eclipsek20** [comment]
Same here

**Comment by yoshiask** [comment]
This issue doesn't seem to have anything to do with proxies, and more to do with localization. The `v9,0` in the URL should be `v9.0`. This bug was supposed to be fixed in 2b6630b7398433f8da9741e69ef4d3a0e9861af8, but clearly it is still present. A fix is being investigated.
