### ISSUE TITLE
No real issue, just WOW!

### ISSUE THREAD

**Issue by Noemata** [yoshiask/FluentStore#4]
Very nice.  I did run into some minor date parsing issues related to Json deserialization.

```
        public async Task<ProductDetailsViewModel> GetProductDetailsAsync(ProductDetails productDetails, CultureInfo culture, RegionInfo region)
        {
            try
            {
                var item = await StorefrontApi.GetProduct(productDetails.ProductId, region.TwoLetterISORegionName, culture.Name);
                var candidate = item.Convert<ProductDetails>().Payload;
                if (candidate?.PackageFamilyNames != null && candidate?.ProductId != null)
                {
                    return new ProductDetailsViewModel(candidate);
                }
                else return null;

            }
            catch (Exception ex)
            {
                // MP! fixme: resolve json parsing issue on dates above
                return null;
            }
        }
```

**Comment by yoshiask** [comment]
Howdy! I'm glad you like the app.

Thanks for pointing out where in the code the error is, can you also provide an example though? Are you in a different region than en-US (since that's all I'm able to test)?

**Comment by Noemata** [comment]
I don't think the region matters, (I'm in Canada).  I used "microsoft corporation" as the search text which comes back with dozens of entries.  It only generates the exception on some of them.  The issue appears to be with the way the data string is formatted.  I've run into this before with JsonConvert.  You sometimes have to pre-parse the date portion of json string to make sure you won't generate an exception.  I think there are a couple workarounds for this out there.

**Comment by Noemata** [comment]
I suggest you throw in some try/catch exception handling with error reporting to the UI.  It's better to error gracefully and not work, than to crash without reason.

**Comment by CarlosOrqueda** [comment]
How is it installed? I would like to try it

**Comment by Noemata** [comment]
@CarlosOrqueda , you'll need to build and deploy the solution.  I found it straightforward.  Leave a comment in here with any specific issues you run into.

**Comment by yoshiask** [comment]
@CarlosOrqueda Howdy, thanks for the interest! The only major caveat you have to worry about for building from source is StoreLib. When you clone the repo, don't forget to grab the submodules.

**Comment by Noemata** [comment]
Any word on a fix for the json date handling problem?

**Comment by yoshiask** [comment]
@Noemata I'm still investigating where that issues comes from, since none of the code I wrote parses anything with dates. It just leaves it as a string or int/long. That means it has to be coming from StoreLib, which is a mildly overcomplicated project with a lot of custom implementations necessary for it to work. It might be a while before I figure out what's wrong and implement a decent fix (not just a temporary workaround).

**Comment by Noemata** [comment]
The problem is with the JSON date string coming back from a Windows Store reply.  NewtonSoft isn't able to handle the format of the date string hence the exception.  I had run into this before.  My solution was to use Microsoft's json deserializer (not a good option in this case).  It is able to handle date formats the NewtonSoft JSON parser does not.  Another option is to adjust the JSON date at the point I provided in the try/catch handler above so the JSON date string is in a format supported by NewtonSoft.

**Comment by yoshiask** [comment]
Yeah, I know that, I'm just saying it's weird there are date deserialization errors because I didn't tell Newtonsoft to deserialize any dates.

**Comment by Noemata** [comment]
Usage is probably in a support lib.  I'll have a look in the next day or so.

**Comment by yoshiask** [comment]
I tried switching my culture to en-CA and searching "microsoft corporation", but I couldn't reproduce the issue. For now, I've pushed a commit that just wraps the request in a try-catch (like you initially suggested), so at least it shouldn't crash.

**Comment by Noemata** [comment]
I think this is where the problem lies:

        public ResponseItem(ResponseItem item)
        {
            if (item != null)
            {
                TypeName = item.TypeName;
                Path = item.Path;
                ExpiryUtc = item.ExpiryUtc;
                Payload = (item.Payload as Newtonsoft.Json.Linq.JObject).ToObject<TPayload>();
            }
        }

I will try to confirm that today.

**Comment by Noemata** [comment]
I was able to confirm that this is where the JSON conversion takes place.  What's interesting is that I'm seeing the exception less often than before, but it still pops up.  Previously I would see it for just about any search which suggests that the problem is some back end issue on Microsoft's side.  I'm going to try to pin this down now.  The Newton date conversion is rather fragile given how complicated the cases are.  At least now we know where the conversion is taking place.

**Comment by Noemata** [comment]
I found the problematic JSON:

{"RevisionId": "2020-12-15T04:11:02.0384876Z||22f9f987-7000-47da-8daf-4fab6851bd6d||PackageVersion1"}

It looks like the ToObject conversion is tripping up on this portion of the object conversion.  I'm not sure what to make of what object this is supposed to map to.  Do you have any ideas?

I added the following to catch the issue:

```
        public ResponseItem(ResponseItem item)
        {
            if (item != null)
            {
                TypeName = item.TypeName;
                Path = item.Path;
                ExpiryUtc = item.ExpiryUtc;
                try
                {
                    Payload = (item.Payload as Newtonsoft.Json.Linq.JObject).ToObject<TPayload>();
                }
                catch(Exception ex)
                {
                    throw;
                }
            }
        }
```

**Comment by Noemata** [comment]
This is definitely the problem. RevisionId is declared as:

```
        public DateTimeOffset RevisionId { get; set; }
```
So a value of 2020-12-15T04:11:02.0384876Z||22f9f987-7000-47da-8daf-4fab6851bd6d||PackageVersion1"} will certainly generate an exception.  I have no clue why the Time Offset would be malformed as it is.  I also think the region you are in is a factor when receiving this data.  I'll try and dig a little deeper.

**Comment by Noemata** [comment]
I made the following change in ProductDetails.cs and the problem goes away for all my searches:

```
        // MP! was:
        //public DateTimeOffset RevisionId { get; set; }
        // MP! changed: To resolve JSON conversion exception.
        //             Type mapping was probably incorrect.
        public string RevisionId { get; set; }
```

It's clear that RevisionId is not a DateTimeOffset value.   The name itself suggests some other sort of mapping.  Leaving it as a string will do for now.

I suggest you change:

```
        public async Task<ProductDetailsViewModel> GetProductDetailsAsync(ProductDetails productDetails, CultureInfo culture, RegionInfo region)
        {
            try
            {
                var item = await StorefrontApi.GetProduct(productDetails.ProductId, region.TwoLetterISORegionName, culture.Name);
                var candidate = item.Convert<ProductDetails>().Payload;
                if (candidate?.PackageFamilyNames != null && candidate?.ProductId != null)
                {
                    return new ProductDetailsViewModel(candidate);
                }
                else return null;

            }
            catch (Exception ex)
            {
                // MP! fixme: resolve json parsing issue on dates above
                return null;
            }
        }
```

GetProductDetailsAsync should return some value other than null so any other JSON conversion issues can be resolved in case there are other incorrect mappings.   Visually showing an error icon with a title consisting of part of the exception is one idea.  You do not need the try/catch in the ResponseItem(ResponseItem item) function call unless you want to frame the error inside of there.

Or

Get a definitive definition of what ProductDetails consists of.  That probably isn't possible given how Microsoft dolls out such information.

**Comment by yoshiask** [comment]
Wow, wonderful investigation! I think the most sensible fix is to make RevisionId a string. Since it's an ID, it doesn't make much sense to have it as a DateTimeOffset. And if for some reason we needed to get a DateTimeOffset from it, we could just split on "||" and parse only the first entry.

Do you want to open a pull request with the change? (You've already basically solved the issue, and I want to make sure you get the credit for your work.)

**Comment by Noemata** [comment]
Agree with making RevisionId a string and the possible split op in future.  I was wondering if you would be interested in adding me as a dev on the repo?  I would only make changes that were agreed on.  I'm already starting to move certain bits along.  I think this could progress much faster if I was contributing directly.  I've started in on adding MVVM into the mix using Microsoft's new MVVM framework.

**Comment by yoshiask** [comment]
I'd be more than happy to give you write access, you seem to know what you're doing. You should have an invite in your email.

I'm already using the MVVM Toolkit, I'm a little confused about what exactly you're doing there. Maybe we should have a separate issue to discuss that.

**Comment by Noemata** [comment]
Fixes added to master.
