### ISSUE TITLE
FluentStore shows nothing

### ISSUE THREAD

**Issue by SleepDaemon** [yoshiask/FluentStore#41]
### Before you start...

- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 10

### What OS/App version/architecture are you seeing the problem on?

Windows 10 21H2 (OS Build 19044.1466)
App version: v0.3.0 Beta 

### Description

Nothing shows on home nor when i search. Yes Windows Store service is running.

![image](https://user-images.githubusercontent.com/88533953/166135415-b3644b58-a01c-4262-8665-c8420f72b1a0.png)
![image](https://user-images.githubusercontent.com/88533953/166135417-3ef9b30d-e716-4214-a6b2-1062555f6971.png)

### Expected behavior

Show app when i search something, like the image below.

![image](https://user-images.githubusercontent.com/88533953/166135451-3295958b-cb63-4a26-8e88-23d28d8a179a.png)

**Comment by lenicyl** [comment]
Im also having the same issue.

Windows : Version 21h2 (OS Build 19044.1645)
Fluent Store : Version 0.3.0

**Comment by yoshiask** [comment]
It seems like it failed to download the default plugins. Have you tried using the "Reset" button in the app settings? That should force it to try again.

**Comment by SleepDaemon** [comment]
> 

I tried that but it didn't do anything

**Comment by SleepDaemon** [comment]
> It seems like it failed to download the default plugins. Have you tried using the "Reset" button in the app settings? That should force it to try again.
> 
> By the way, Fluent Store does not use the Microsoft Store service. It shouldn't matter if it's running or not, at least not for viewing packages (installing is a different story)

I tried that but it didn't work, also I was referring that you need the service enabled to install FluentStore.

**Comment by SleepDaemon** [comment]
Tried reinstalling but that didn't work either. Gonna uninstall it and install.

**Comment by SleepDaemon** [comment]
> Tried reinstalling but that didn't work either. Gonna uninstall it and install.

nope that didn't work either, im fully out of ideas other than I manually add the plugins myself but I don't know where to get the plugins from.

**Comment by yoshiask** [comment]
> Tried reinstalling but that didn't work either. Gonna uninstall it and install.

Uninstalling does not clear the app's settings, you have to use the button in the app.

**Comment by SleepDaemon** [comment]
> > Tried reinstalling but that didn't work either. Gonna uninstall it and install.
> 
> Uninstalling does not clear the app's settings, you have to use the button in the app.

@yoshiask well I already told you the reset button didn't do anything

**Comment by aqtsalt** [comment]
same an i just installed it for the first time, had to install previous version

**Comment by yoshiask** [comment]
> same an i just installed it for the first time, had to install previous version

Which version of Windows are you on?

**Comment by SleepDaemon** [comment]
> same an i just installed it for the first time, had to install previous version

Same, I decided to do what you did and install the older version and that works for me. Here is my windows version:
![image](https://user-images.githubusercontent.com/88533953/167152677-b4f4a4a7-e743-4e57-a7e5-643127f5b2b0.png)

**Comment by yoshiask** [comment]
Howdy! I believe this has been fixed server-side. If you have experienced this issue, please try deleting the following folder and resetting Fluent Store:
`%appdata%\..\Local\FluentStoreBeta\Plugins`

**Comment by SleepDaemon** [comment]
> Howdy! I believe this has been fixed server-side. If you have experienced this issue, please try deleting the following folder and resetting Fluent Store: `%appdata%\..\Local\FluentStoreBeta\Plugins`

Hi, sadly my apppackage installer is broken. So I'm force to use the previous version which is a .exe, reason for it being broken is because my windows is broken and can't fix it either.

**Comment by yoshiask** [comment]
@SleepDaemon This is expected, the location of the installer changed as part of the fix for this issue. I'm not able to fix the GitHub Release at the moment, but you can download the fixed version from here:
https://ipfs.askharoun.com/FluentStore/BetaInstaller/FluentStoreBeta.appinstaller

**Comment by SleepDaemon** [comment]
> @SleepDaemon This is expected, the location of the installer changed as part of the fix for this issue. I'm not able to fix the GitHub Release at the moment, but you can download the fixed version from here: https://ipfs.askharoun.com/FluentStore/BetaInstaller/FluentStoreBeta.appinstaller

When I click the link it just takes me to this.
![image](https://user-images.githubusercontent.com/88533953/176593872-b3e049c5-4739-4089-a685-3f43b5d8765f.png)

**Comment by yoshiask** [comment]
Oh, you can just save that as a file and open it. Or you can wait about 30 seconds for me to fix that 😄

**Comment by yoshiask** [comment]
> Oh, you can just save that as a file and open it. ~Or you can wait about 30 seconds for me to fix that 😄~
> 
> Hmm, my fix didn't work. I'll have to investigate this later, but for now just hit Ctrl-S and save as.

The save issue has been fixed server-side, you should be able to go to [ipfs.askharoun.com/FluentStore/BetaInstaller/FluentStoreBeta.appinstaller](https://ipfs.askharoun.com/FluentStore/BetaInstaller/FluentStoreBeta.appinstaller) and it will download the update installer.

**Comment by SleepDaemon** [comment]
> > Oh, you can just save that as a file and open it. ~Or you can wait about 30 seconds for me to fix that 😄~
> > Hmm, my fix didn't work. I'll have to investigate this later, but for now just hit Ctrl-S and save as.
> 
> The save issue has been fixed server-side, you should be able to go to [ipfs.askharoun.com/FluentStore/BetaInstaller/FluentStoreBeta.appinstaller](https://ipfs.askharoun.com/FluentStore/BetaInstaller/FluentStoreBeta.appinstaller) and it will download the update installer.

Installed it, launched the app, shows the fluentstore loading icon and then it closes itself

**Comment by SleepDaemon** [comment]
I think I need completely delete any remains of Fluentstore, the appinstaller you provided work but now it doesnt launch. It just shows loading screen and then crashes or closes.

**Comment by yoshiask** [comment]
> I think I need completely delete any remains of Fluentstore, the appinstaller you provided work but now it doesnt launch. It just shows loading screen and then crashes or closes.

This is an unrelated issue many users have been seeing on non-preview versions of Windows. I'll open a separate bug report for that.

**Comment by SleepDaemon** [comment]
> > I think I need completely delete any remains of Fluentstore, the appinstaller you provided work but now it doesnt launch. It just shows loading screen and then crashes or closes.
> 
> This is an unrelated issue many users have been seeing on non-preview versions of Windows. I'll open a separate bug report for that.

I've got many folks asking if there is a .exe for FluentStore, since they don't have the app installer from the MS store.

**Comment by yoshiask** [comment]
I believe this issue has been fixed. If you're still having issues, please file a new report.

**Comment by yoshiask** [comment]
> I've got many folks asking if there is a .exe for FluentStore, since they don't have the app installer from the MS store.

Why don't they have App Installer? If they're on a version of Windows that doesn't ship with it, it's also too old to run Fluent Store. If they ran a debloat script that removed it, they likely also broke the package management APIs that Fluent Store depends on. If you would like to advocate for this feature, please open a new issue so I can track it there.
