### ISSUE TITLE
FluentStore Crashes on Launching

### ISSUE THREAD

**Issue by SleepDaemon** [yoshiask/FluentStore#45]
### Before you start...

- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 10

### What OS/App version/architecture are you seeing the problem on?

FluentStore version 3

### Description

FluentStore version 3, when I open the app it launches and shows loading screen but it then simply closes itself or its crashing.

### Steps To Reproduce

1. Open the app
2. let load (loading screen)
3. it crashes or closes

### Expected behavior

Suppose to load into FluentStore it self

**Comment by SleepDaemon** [comment]
Version 2 still works

**Comment by hedhehd** [comment]
I'm having the exact same issue

**Comment by hedhehd** [comment]
> Version 2 still works

It does but has no content

**Comment by hedhehd** [comment]
It's the same for windows 11

**Comment by yoshiask** [comment]
This bug should be fixed in v0.3.1-beta.
