### ISSUE TITLE
Duplicate entries shown for the same item:

### ISSUE THREAD

**Issue by Noemata** [yoshiask/FluentStore#5]
When performing a search, occasionally duplicate entries are shown:

![image](https://user-images.githubusercontent.com/6632315/103549714-cf3db500-4e75-11eb-85d2-b7ddda799fc0.png)

Notice how "World of Bamboo PREMIUM" shows up twice.  I'm just guessing, but is this possibly due to the way the internal list gets added to?  I haven't looked at that part of the code, but it looks like a simple overlap problem.

**Comment by yoshiask** [comment]
Fixed in commit f474d63faf2babfcc723e77b28042b1eae532a21
