### ISSUE TITLE
0.3.2 still not working

### ISSUE THREAD

**Issue by SleepDaemon** [yoshiask/FluentStore#50]
### Before you start...

- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 10

### What OS/App version/architecture are you seeing the problem on?

![image](https://user-images.githubusercontent.com/88533953/181699517-8450f38f-d29a-4b1b-9499-0cc1be875ce5.png)

### Description

this is on msix, I tried appinstaller but that does nothing.

### Expected behavior

app should install

**Comment by yoshiask** [comment]
Which build of Windows 10 is this? Do you have the Microsoft Store installed?

**Comment by SleepDaemon** [comment]
> Which build of Windows 10 is this? Do you have the Microsoft Store installed?

It is debloated I will admit that, the amount of bloat made my laptop very slow and after removing it the experience was way better but of course windows updates try to undo these debloats but fails at it and causing it to break. Also there is something called Windows LTSC which a windows version that doesn't have any bloat nor does it ship with microsoft store. I understand if you wish not to create a .exe or any form way to aid debloaters.
![image](https://user-images.githubusercontent.com/88533953/181790786-1d9298a2-c62d-4719-9d3c-4d258f87e12e.png)

**Comment by yoshiask** [comment]
I'll see what I can do regarding EXE installers in #50.

As for your installation issue, I suspect App Installer is unable to download a required dependency that is usually available from the MS Store. I don't have access to a computer at the moment, but I think the package you need is `Microsoft.VCLibs.140.00`. I'll see if I can find a download for this and potentially add it to the Fluent Store installer.

**Comment by yoshiask** [comment]
I'll see what I can do regarding EXE installers in #50.

As for your installation issue, I suspect App Installer is unable to download a required dependency that is usually available from the MS Store. I don't have access to a computer at the moment, but I think the package you need is `Microsoft.VCLibs.140.00`. I'll see if I can find a download for this and potentially add it to the Fluent Store installer.

**Comment by yoshiask** [comment]
Does this installer work for you?
https://ipfs.askharoun.com/FluentStore/BetaInstaller/FluentStoreBeta.appinstaller

**Comment by SleepDaemon** [comment]
> Does this installer work for you? https://ipfs.askharoun.com/FluentStore/BetaInstaller/FluentStoreBeta.appinstaller

![image](https://user-images.githubusercontent.com/88533953/181876219-97430825-9dd4-4fc0-b6fc-9b5a1e0e37c0.png)

**Comment by yoshiask** [comment]
That looks like a system-level issue, there's no way around that on my end, sorry.

**Comment by SleepDaemon** [comment]
i see well i guess .exe would be the work around if you wish to make one. Not asking to make one just for me.
