### ISSUE TITLE
Fluent Store as .exe

### ISSUE THREAD

**Issue by SleepDaemon** [yoshiask/FluentStore#51]
### Before you start...

- [X] Have you checked if similar request have already been reported?

### Description

Fluent Store is a greate alternative to ms store, in which some people remove while debloating. Creating .exe means they wont need microsoft api to install it, or you can create an .msi

**Comment by yoshiask** [comment]
Debloat scripts often remove more than just the MS Store app itself, which breaks App Installer and potentially even Fluent Store itself (FS uses the same package management APIs the MS Store app does).

I might look into this anyway for enterprise users that have disabled MS Store via policy, but debloat scripts are not supported.

**Comment by ripnonfegames** [comment]
I don't have app installer, i'm trying to but it won't let me.

**Comment by yoshiask** [comment]
@ripnonfegames Every supported version of Windows (except some Enterprise installs) has App Installer. Which version are you running?

**Comment by ripnonfegames** [comment]
Well I reset LTSC and it didn't have app installer, I got it working though after resetting twice haha

**Comment by yoshiask** [comment]
Closing this as unplanned for now, as debloat scripts are not a supported configuration. Might come back to it for Enterprise or LTSC users in the future.
