### ISSUE TITLE
Please add additional info for viewing

### ISSUE THREAD

**Issue by Skrell** [yoshiask/FluentStore#53]
### Before you start...

- [X] Have you checked if similar request have already been reported?

### Description

The default Window's Store displays a lot more information about each App.  (See picture below) and I can't seem to see this same info using FluentStore

Win10x64

![image](https://user-images.githubusercontent.com/590266/182035052-009e77a8-2b27-46d8-a529-cedb72423bdd.png)

vs

![image](https://user-images.githubusercontent.com/590266/182035125-5c7baf4c-4569-4e06-854e-33d2eef8e833.png)

**Comment by yoshiask** [comment]
The app page has a scrollbar, most of that information (including the description and review summary) is further down on the page.

**Comment by Skrell** [comment]
I'm an idiot, thank you!

**Comment by yoshiask** [comment]
No you're not, it's not obvious there's more to see. The next release has a "more details" button that brings the details into view if they might be hidden.
