### ISSUE TITLE
microsoft account login

### ISSUE THREAD

**Issue by HarkTu** [yoshiask/FluentStore#54]
### Before you start...

- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 10

### What OS/App version/architecture are you seeing the problem on?

windows 10 19044.1889
app 0.3.2

### Description

error when click login button
![Screenshot_2](https://user-images.githubusercontent.com/46054251/184002450-961faab0-c9ae-48aa-9a2d-feea2114be03.png)

### Expected behavior

login

**Comment by yoshiask** [comment]
This is a known issue with the Windows App SDK, the latest patch for the MS Store plugin started using a feature that's bugged in current WinAppSDK releases. I'll see if I can release a hotfix that reverts the change, but either way there's no point to signing into a Microsoft Account at the moment.

**Comment by yoshiask** [comment]
This crash has been resolved with the release of v0.3.3-beta.
