### ISSUE TITLE
Replace Microsoft Store link type

### ISSUE THREAD

**Issue by ThreeDeeJay** [yoshiask/FluentStore#58]
### Before you start...

- [X] Have you checked if similar request have already been reported?

### Description

It would be handy if FluentStore could replace Microsoft Store as the default link for apps/sites that try to open up specific store apps.

### Relevant Assets

![image](https://user-images.githubusercontent.com/71472458/197388316-41abe492-0d3e-48aa-ad4b-8fcf3a19284b.png)

**Comment by yoshiask** [comment]
This is unfortunately not possible. `ms-store` is one of a handful of locked-down protocols, meaning Windows won't let anyone else register as a handler for it.

**Comment by yoshiask** [comment]
There may be a hacky way to accomplish it, but I'm not aware. I will look into it again though.

As a side note, removing the Microsoft Store might also remove components that Fluent Store and App Install rely on. I would not recommend that.
