### ISSUE TITLE
Getting this error and installing gets stuck

### ISSUE THREAD

**Issue by SleepDaemon** [yoshiask/FluentStore#60]
### Before you start...

- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11

### What OS/App version/architecture are you seeing the problem on?

App: latest v0.3.2
Architecture: x86 CPU

### Description

![image](https://user-images.githubusercontent.com/88533953/216009004-7b5101a4-8152-4df0-826d-c8be82c0c18f.png)

The other problem is that if I try installing an app from fluent store, it just stuck on downloading. But looking at glasswire, it reports I have downloaded 1.8gb from fluent.

### Expected behavior

App shouldn't give this pop up and installing shouldnt get stuck.

**Comment by yoshiask** [comment]
The FuseSharp error message is a known issue with searching, you should be able to safely ignore it until it's fixed.

When you say "stuck on downloading", are you still able to interact with the app? Also, were you trying to download and install or just download the app?

**Comment by SleepDaemon** [comment]
The app lags a bit but still able to move, also I just click the button on
the app page that just downloads/installs it. It gets stuck where it it
says "downloading" for the progress bar.

**Comment by SleepDaemon** [comment]
> Interesting. Do you remember which app this was happening with? Does it happen with more than one, or apps from a particular source (WinGet, MS Store, etc.)?

It happened on 2 apps I tried downloading, as for which source I don't know. Cause I don't where it is indicated which source it is downloading from.

**Comment by SleepDaemon** [comment]
The apps were Intel Unison, Files app, and Link Phone. I don't remember exactly if these were the ones.

**Comment by yoshiask** [comment]
v0.3.3-beta has just been released, do you still get this error with that version?
