### ISSUE TITLE
v0.3.2 Beta

### ISSUE THREAD

**Issue by OrangeCat2018** [yoshiask/FluentStore#61]
### Stated in https://github.com/yoshiask/FluentStore/discussions/48

**Hello,**

I've recently became aware of this project/app, although, upon my attempts to install v0.3.2 (first initial install) I keep receiving:
 _"App installation failed with error message: Class not registered (0x80040154)"_

 
**Wondering if anyone would kindly be able to provide me with some resolution-feedback**

 
 
...
**To go in details about undertaken steps (for troubleshooting purposes):**

Following some quick google searches _using criteria: "Class not registered (0x80040154)"_,
it was suggested that I install the following runtime:
- C++ Runtime v11.0 framework package for Desktop Bridge (Project Centennial)
- C++ Runtime v12 framework package for Desktop Bridge (Project Centennial)

_Although, the installation of those above mentioned-runtime(s) didn't solve this particular issue..._

 

**As for my installation process...**

I've acquired both 
 -   FluentStoreBeta.appinstaller
 -   FluentStoreBeta_0.3.2_2.msixbundle

I first executed **msixbundle** _which resulted to a "Class not registered (0x80040154)" error message._
and then executed **appinstaller** _which also resulted to a "Class not registered (0x80040154)" error message._

 
 
**As for the "executed from" local destination path**

Having altered my OS's default profile basic-folders location..
Both were executed from "D:\Admin\OS\W10\Users\Andre\Download"
(not sure if not being in proper drive letter can be an issue, as I did prior experience a few .exe fail in the past due to this)

**Comment by yoshiask** [comment]
Howdy! Sorry to hear you're having issues. Having the installer on a separate drive shouldn't cause any issues, I do the same on my own computers. Just to be sure, have you run any debloat scripts or applied any tweaks?

**Comment by OrangeCat2018** [comment]
I use Ghostspectre Windows 10 Pro x64 AIO Update 8, (22h2? i think?
whichever the most latest one is)

If familiar with his work, then the option I use is the SuperLite without
defender, without StartIsBack (as I prefer OpenShell)



Although...

Yes, I did run a registry thing (name of program escapes me) as I was
looking for a way to backup registry entries without resulting to having
any hex conversion...

This tool came with a scanner thing that proceeded and stated that it fixed
over 500 registry errors (which was odd as I had just recently
formatted/re-installed windows that same-morning)

furthermore, that tool changed sone stuff that i dislike, such as menu
popup speed and etc.. and it did not even solve the fact that registry
backups creates hex conversion (something i wanted to have as string
instead).

**Comment by yoshiask** [comment]
It seems like Ghostspectre removes Windows components that are critical for App Installer and Fluent Store. Even if you managed to get Fluent Store installed, it would be unable to install most programs. As such, I cannot support this configuration. Sorry there's nothing I can do, unless those components can be reinstalled.
