### ISSUE TITLE
"Failed to download packages using WindowsUpdateLib at [...] MicrosoftStorePackage.cs:line 57"

### ISSUE THREAD

**Issue by KaKi87** [yoshiask/FluentStore#65]
### Before you start...

- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 10

### What OS/App version/architecture are you seeing the problem on?

Windows 10 19045.2965, 64-bit, Fluent Store 0.3.2

### Description

Download's progress goes forward and backwards repeatedly then fails with an error.

### Steps To Reproduce

1. Search for a Microsoft Store app
2. Try installing it
3. See progress go forward
4. See progress go backwards
5. See error

### Expected behavior

Download's progress only goes forward then succeeds.

### Relevant Assets

![](https://github.com/yoshiask/FluentStore/assets/21284089/9a4ace53-39f0-4b40-945b-45ac4245b1a6)

---

Thanks

**Comment by yoshiask** [comment]
v0.3.3-beta has just been released, do you still get this error with that version?
