### ISSUE TITLE
Crashes when trying to open roblox package

### ISSUE THREAD

**Issue by ripnonfegames** [yoshiask/FluentStore#66]
### Before you start...

- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 10

### What OS/App version/architecture are you seeing the problem on?

Windows 10 LTSC, latest version.

### Description

Self explanatory, if you even try to open the roblox app, the whole thing crashes. It cannot be installed by winget either due to the installer hash not matching.

### Steps To Reproduce

1. Search for roblox.
2. Tap roblox.
3. Fluent store crashes.

### Expected behavior

1. Search for roblox.
2. Tap roblox
3. See the preview for the app
4. Install roblox

**Comment by yoshiask** [comment]
Howdy! Thanks for reporting this issue. I have been able to reproduce the crash with the Winstall listing of Roblox.

**Comment by yoshiask** [comment]
Completed and released in v0.3.3-beta

**Comment by ripnonfegames** [comment]
Hold on, now it won't let me install it. It will say completed but it's not there.
