### ISSUE TITLE
Search does not work, nor does the Home page.

### ISSUE THREAD

**Issue by ripnonfegames** [yoshiask/FluentStore#68]
### Before you start...

- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 10

### What OS/App version/architecture are you seeing the problem on?

Windows 10 LTSC.

### Description

Searching comes up with "We couldn't find anything matching "%NAME%". Try searching again with different terms.

### Steps To Reproduce

1. Search for literally anything, E.G solitaire.
2. Success

or

1. Open homepage
2. See blank

### Expected behavior

1. Search for literally anything
2. Get results

or
1. Open homepage
2. See things

### Relevant Assets

![image](https://github.com/yoshiask/FluentStore/assets/56087561/81ef78ea-593e-4b62-b37c-47e55195e96e)

**Comment by yoshiask** [comment]
Does the workaround in the README resolve this?
https://github.com/yoshiask/FluentStore#ive-just-installed-fluent-store-and-my-home-page-is-blank

**Comment by ripnonfegames** [comment]
> Does the workaround in the README resolve this? https://github.com/yoshiask/FluentStore#ive-just-installed-fluent-store-and-my-home-page-is-blank

It fixed both the search and home page, thanks!
