### ISSUE TITLE
Show Permissions in app info

### ISSUE THREAD

**Issue by e-t-l** [yoshiask/FluentStore#75]
### Before you start...

- [X] Have you checked if similar request have already been reported?

### Description

In the Microsoft Store, app info includes Permission Info, which describes what parts of the system an app would have access to. This would be helpful information to have before installing something!

**Comment by yoshiask** [comment]
Howdy! Thanks for filing this, it should be fixed in the next release.
![image](https://github.com/user-attachments/assets/0e37cd01-9cde-4a31-b4cc-d123349c1380)
